services:
    oberon_brewery_data:
        class: AppBundle\Service\OberonBreweryData
        arguments: ["@doctrine.orm.entity_manager"]
    google_maps_distance_matrix:
        class: AppBundle\Service\GoogleMapsDistanceMatrix
        arguments: ['%google_maps_api_key%']